# -*- coding: utf-8 -*-
"""Support_Vector_Machine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BkqwzJctthBMWdO6UCWRiSRU2YiC88m
"""

import matplotlib.pyplot as plt
import numpy as np

from sklearn.datasets import fetch_lfw_people

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

lfw_people = fetch_lfw_people(min_faces_per_person = 70, resize=0.4)
n_samples, h, w = lfw_people.images.shape
lfw_people.images.shape

X=lfw_people.data
n_features = X.shape[1]
y=lfw_people.target
target_names = lfw_people.target_names
n_classes=target_names.shape[0]

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.25, random_state=42)

C=1000

clf=SVC(kernel='linear', class_weight='balanced', C=C)
clf=clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

print(classification_report(y_test, y_pred, target_names=target_names))
print(confusion_matrix(y_test, y_pred, labels=range(n_classes))m)

pred_name=target_names[y_pred[1]]
print(pred_name)

plt.figure(figsize=(12, 12))
plt.subplots_adjust(bottom=0, left=.01, right=.99, top=.90, hspace=.35)
for i in range(12):
  plt.subplot(3, 4, i+1)
  plt.imshow(X_test[i].reshape((h, w)), cmap=plt.cm.gray)
  plt.title('predicted: %s\ntrue:          %s' % (target_names[y_pred[i]], target_names[y_test[i]]))